/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afeafngui;

import afeconverterafn.*;
import java.util.StringTokenizer;

/**
 *
 * @author Susane Xavier
 */
public class gui extends javax.swing.JFrame {
    
    Automata afe = new Automata();
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Automato");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {"", null, null, null, null},
                {"", null, null, null, null},
                {"", null, null, null, null},
                {"", null, null, null, null},
                {"", null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "δ", "Símbolo 1", "Símbolo 2", "Símbolo 3", "ε"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jToggleButton1.setText("Converter");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "δ", "Símbolo 1", "Símbolo 2", "Símbolo 3"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        jToggleButton1.setEnabled(false);
        String ID;
        jTable1.validate();
        jTable1.updateUI();
        
        for(int i = 0; i < 7; i++){
            
            if(jTable1.getValueAt(i, 0) != null){
                ID = (String)jTable1.getValueAt(i, 0);
                if(!ID.isEmpty()){
                    
                    if(ID.contains("0"))
                        afe.addStateInicial(new State(ID));
                    else if(ID.contains("f") || ID.contains("F"))
                        afe.addStateFinal(new State(ID));
                    else
                        afe.addState(new State(ID));
                }
            }
        }

        for(int i = 0; i < 7; i++){
            if(jTable1.getValueAt(i, 0) != null){
                ID = (String) jTable1.getValueAt(i, 0);
                if(ID.contains("q") || ID.contains("Q")){
                    if(jTable1.getValueAt(i, 1) != null){
                        StringTokenizer token = new StringTokenizer((String)jTable1.getValueAt(i, 1), ",");
                        afe.addAlphabeto("a");
                        while(token.hasMoreTokens()){
                            afe.addTransitionState(ID, new Transition("a", afe.deltaFindState((String)token.nextToken())));
                        }
                    }
                    if(jTable1.getValueAt(i, 2) != null){
                        StringTokenizer token = new StringTokenizer((String)jTable1.getValueAt(i, 2), ",");    
                        afe.addAlphabeto("b");
                        while(token.hasMoreTokens()){
                            afe.addTransitionState(ID, new Transition("b", afe.deltaFindState((String)token.nextToken())));
                        }
                    }
                    if(jTable1.getValueAt(i, 3) != null){
                        StringTokenizer token = new StringTokenizer((String)jTable1.getValueAt(i, 3), ",");    
                        afe.addAlphabeto("c");
                        while(token.hasMoreTokens()){
                            afe.addTransitionState(ID, new Transition("c", afe.deltaFindState((String)token.nextToken())));
                        }
                    }
                    if(jTable1.getValueAt(i, 4) != null){
                        StringTokenizer token = new StringTokenizer((String)jTable1.getValueAt(i, 4), ",");    
                        afe.addAlphabeto("ε");
                        while(token.hasMoreTokens()){
                            afe.addTransitionState(ID, new Transition("ε", afe.deltaFindState((String)token.nextToken())));
                        }
                    }
                }
            }
        
            Automata afn = afe.converter();
            for(int ss = 0; ss < 7; ss++){
                State n = afn.getState(ss);
                if(n != null){
                    jTable2.setValueAt(n.getID(), ss, 0);
                    jTable2.setValueAt(n.getTransitions("a"), ss, 1);
                    jTable2.setValueAt(n.getTransitions("b"), ss, 2);
                    jTable2.setValueAt(n.getTransitions("c"), ss, 3);
                }else
                    break;
            }
        }
        jTable2.setEnabled(true);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
